import math

# Display settings
DISPLAY_WIDTH = 1920
DISPLAY_HEIGHT = 1080
DISPLAY_CENTER = (DISPLAY_WIDTH // 2, DISPLAY_HEIGHT // 2)
FONT_SIZE = 28

# Movement factors
DIAGONAL_SPEED_FACTOR = math.sqrt(2) / 2
